### ISSUE TITLE
Cannot find module 'simplebar-vue3' or its corresponding type declarations.ts(2307)

### ISSUE THREAD

**Issue by anburocky3** [teamseodo/simplebar-vue3#12]
Type definitions for typescript projects?

For time being, i have created the `types` in my `types/index.ts` file 

```ts
declare module "simplebar-vue3";
```

**Comment by kadiryazici** [comment]
I didn't get what you mean. I installed library and types were ok.

Are you sure you're using last version? in 0.1.7 we had some vite build issues

<img width="1019" alt="CleanShot 2022-09-07 at 18 08 53@2x" src="https://user-images.githubusercontent.com/47540799/188914263-db5ed5d3-a71f-4d3e-bc79-92fee6cebed1.png">

**Comment by anburocky3** [comment]
I receive this error while using it inside my template


![image](https://user-images.githubusercontent.com/15264938/188915589-a38542fe-b358-4571-9956-5ea82e776284.png)

**Comment by kadiryazici** [comment]
@anburocky3 it's weird, now we have to put `?` for events as well. Not to have somthing like this in future instead of writing types by hand I will add `vite-plugin-dts` plugin.

Volar changes soo quickly.

<img width="1607" alt="CleanShot 2022-09-07 at 18 32 18@2x" src="https://user-images.githubusercontent.com/47540799/188918896-5bba39bb-ef3e-4495-94f8-2b2be97190aa.png">

**Comment by kadiryazici** [comment]
@anburocky3 This [PR](https://github.com/wopehq/simplebar-vue3/pull/13) will fix every present and future type issues.

**Comment by anburocky3** [comment]
> @anburocky3 This [PR](https://github.com/wopehq/simplebar-vue3/pull/13) will fix every present and future type issues.

Thanks, looking forward for the merge.

**Comment by kadiryazici** [comment]
@anburocky3 0.2.0 is a Minor change, it has breaking changes. Changelog has informations.
